### ISSUE TITLE
Проверить ДЗ №5 - Калькулятор затрат

### ISSUE THREAD

**Issue by lerucom** [lerucom/js-homework5#1]
@coursar
Развертывание GitHub Pages https://lerucom.github.io/js-homework5/
* Нужна помощь: не пойму как писать тесты для этого задания, получился лишь 1 тест.

**Comment by coursar** [comment]
1-ый тест: в корзинке пара товаров, вы ищете сумму (уже у вас написан)
2-ой тест: в корзинке пара товаров, вы ищете самый дорогой
3-ий тест: в корзинке нет товаров, вы ищете сумму - должна быть 0
4-ый тест: в корзинке нет товаров, вы ищете самый дорогой - что должно быть?
