### ISSUE TITLE
Лучше из метода возвращать данные, а не строку, тогда не будет проблем с локализацией позже

### ISSUE THREAD

**Issue by coursar** [lerucom/js-homework5#5]
https://github.com/lerucom/js-homework5/blob/f8770d9dbae666c988ff767e39723528cf7343d8/src/js/lib.js#L19

**Comment by lerucom** [comment]
@coursar 
Ильназ, т.е. вернуть массив из двух значений или объект например?

**Comment by coursar** [comment]
Лучше объект, если это разные данные (например название и стоимость)

**Comment by lerucom** [comment]
@coursar 
Исправил, теперь возвращается объект 124e9f3d6f78e76a8d14a48eb140ba41a47bb91e
